apiVersion: apps/v1
kind: Deployment
metadata: 
  name: notification
  labels: 
    app: notification
spec: 
  replicas: 4
  selector: 
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata:
      labels:
        app: notification
    spec: 
      containers:
        - name: notification
          image: csellers15/notification
          resources: 
            limits:
              memory: 600Mi
              cpu: "1"
          envFrom: 
            - configMapRef:
                name: notification-configmap
            - secretRef:
                name: notification-secret
